# Generated by Django 4.1.6 on 2023-02-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['_id']},
        ),
    ]
