products = [
    {
      '_id': 1,
      'name': 'Baby Blues',
      'image': '/images/babyblue-dress.jpeg',
      'description':
        'Baby blue dress with a soft breathing fabric',
      'brand': 'Jimmy',
      'category': 'Dresses',
      'price': 199,
      'countInStock': 0,
      'rating': 4.5,
      'numReviews': 12,
    },
    {
      '_id': 2,
      'name': 'The Godess',
      'image': '/images/godess-dress.jpeg',
      'description':
        'Beautiful dress with a godess vibe to it',
      'brand': 'Godiva',
      'category': 'Dresses',
      'price': 159,
      'countInStock': 7,
      'rating': 4.0,
      'numReviews': 8,
    },
    {
      '_id': 3,
      'name': 'Spicy Mama',
      'image': '/images/sexy-red-dress.jpeg',
      'description':
        'This hot elegant dress will make you feel and look sexier than ever!',
      'brand': 'Jimmy',
      'category': 'Dresses',
      'price': 310,
      'countInStock': 5,
      'rating': 4.8,
      'numReviews': 16,
    },
    {
      '_id': 4,
      'name': 'Mini Tans',
      'image': '/images/mini-tan-dress.jpeg',
      'description':
        'Mini Dress, super cute!',
      'brand': 'Eanie Mini',
      'category': 'Dresses',
      'price': 120,
      'countInStock': 11,
      'rating': 4,
      'numReviews': 8,
    },
    {
      '_id': 5,
      'name': 'Party Up!',
      'image': '/images/party-dress.jpeg',
      'description':
        'Dress up, its party time, and youre definitly going to shine bright like a diamond - wearing this one here!',
      'brand': 'Diamonds',
      'category': 'Dresses',
      'price': 179,
      'countInStock': 7,
      'rating': 4.5,
      'numReviews': 10,
    },
    {
      '_id': 6,
      'name': 'Prom Queen',
      'image': '/images/prom-dress.jpeg',
      'description':
        'You better get ready for that prom crown',
      'brand': 'PromNights',
      'category': 'Dresses',
      'price': 215,
      'countInStock': 3,
      'rating': 4,
      'numReviews': 12,
    },
  ]
  
